[package]
name = "sinais-decorators"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
tokio = { version = "1", features = ["full"] }
proc-macro2 = "1.0.78"
